wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1726429544
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 76
      3:
      - 13
      - 23
      4: 3.9.18
      5: 0.17.4
      8:
      - 3
      - 5
      13: windows-amd64
