wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721212179
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.9.19
      5: 0.17.4
      8:
      - 5
      13: linux-x86_64
target_encoding:
  desc: null
  value: CNN_RNN
seed:
  desc: null
  value: 0
wandb_proj:
  desc: null
  value: DeepPurposePP
