wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.17.4
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721991417
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 76
      3:
      - 13
      - 23
      4: 3.9.18
      5: 0.17.4
      8:
      - 3
      - 5
      13: windows-amd64
target_encoding:
  desc: null
  value: PAGTN
seed:
  desc: null
  value: 42
wandb_proj:
  desc: null
  value: DeepPurposePP
lr:
  desc: null
  value: 1.0e-05
epochs:
  desc: null
  value: 60
